name: Publish

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release & Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write # Needed for npm provenance

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js 22.14.0
        uses: actions/setup-node@v4
        with:
          node-version: "22.14.0"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run Tests
        run: npm run test

      - name: Build Library
        run: npm run build

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.ALL_TOKEN }}
        run: npx semantic-release
